/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

import MySQL.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Wilthouk
 */
public class InsertarPartidos extends javax.swing.JFrame {

    /**
     * Creates new form InsertarPartidos
     */
    public InsertarPartidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nomequipoL = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomequipoV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        marcadorL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        marcadorV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomestadio = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("ID de la nueva jornada:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 25, 160, 15);
        getContentPane().add(id);
        id.setBounds(32, 50, 240, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("Nombre del equipo Local:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 170, 15);
        getContentPane().add(nomequipoL);
        nomequipoL.setBounds(32, 113, 240, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("Nombre del equipo Visitante: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(32, 151, 190, 15);
        getContentPane().add(nomequipoV);
        nomequipoV.setBounds(32, 176, 240, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 153));
        jLabel4.setText("Marcador Local:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(32, 214, 120, 15);
        getContentPane().add(marcadorL);
        marcadorL.setBounds(32, 239, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setText("Marcador Visitante");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(32, 277, 130, 15);
        getContentPane().add(marcadorV);
        marcadorV.setBounds(32, 302, 100, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setText("Fecha del partido:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 340, 140, 15);
        getContentPane().add(fecha);
        fecha.setBounds(32, 365, 139, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setText("Nombre del estadio:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(32, 403, 140, 15);
        getContentPane().add(nomestadio);
        nomestadio.setBounds(32, 423, 139, 20);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/BotonVolver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(270, 430, 100, 25);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/BotonAceptar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(280, 390, 91, 25);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/FondoTablas.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 730, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        String sSQL="";
        try
        {
            Connection conexion;
            conexion=Conexion.obtener();
            //sSQL = "Insert Into partidos (id_Jornada, Ubicacion) values ('"+id.getText()+"','"+ubi.getText()+"');";
    
    try
    {
        Statement st = (Statement) conexion.createStatement();
        st.executeUpdate(sSQL);
    }
    catch(SQLException ex){
        JOptionPane.showMessageDialog(null,ex);  
    }
    
}       catch (SQLException ex) {
            Logger.getLogger(InsertarEstadios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InsertarEstadios.class.getName()).log(Level.SEVERE, null, ex);
        }
       
      // nom.setText("");
       //ubi.setText("");
                                              

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Insertar v=new Insertar();
        v.setVisible(true);
        this.setVisible(false);
        
        //LIMPIAR PANTALLA ANTES DE SALIR
        //FALTA QUEDAR DE ACUERDO CON MAU PARA LOS CAMPOS//
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarPartidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField marcadorL;
    private javax.swing.JTextField marcadorV;
    private javax.swing.JTextField nomequipoL;
    private javax.swing.JTextField nomequipoV;
    private javax.swing.JTextField nomestadio;
    // End of variables declaration//GEN-END:variables
}
