/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack;

/**
 *
 * @author Wilthouk
 */
public class ModificarPartidos extends javax.swing.JFrame {

    /**
     * Creates new form ModificarPartidos
     */
    public ModificarPartidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomEquipoL = new javax.swing.JTextField();
        cbxIDPartido = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbxIDJornada = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomEquipoV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        MarcadorV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxIDEstadio = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        MarcadorL = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(451, 411));
        setMinimumSize(new java.awt.Dimension(451, 411));
        setPreferredSize(new java.awt.Dimension(451, 411));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("ID del partido a modificar: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 40, 200, 15);
        getContentPane().add(nomEquipoL);
        nomEquipoL.setBounds(220, 100, 190, 20);

        getContentPane().add(cbxIDPartido);
        cbxIDPartido.setBounds(220, 40, 28, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 153));
        jLabel2.setText("ID de la jornada del partido: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 70, 190, 15);

        getContentPane().add(cbxIDJornada);
        cbxIDJornada.setBounds(220, 70, 28, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("Nombre del equipo Local: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 170, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 153));
        jLabel4.setText("Nombre del equipo Visitante:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 144, 220, 15);
        getContentPane().add(nomEquipoV);
        nomEquipoV.setBounds(223, 141, 190, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 153));
        jLabel5.setText("Marcador Visitante:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 220, 130, 15);
        getContentPane().add(MarcadorV);
        MarcadorV.setBounds(220, 220, 190, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setText("Fecha del partido:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 260, 110, 10);
        getContentPane().add(fecha);
        fecha.setBounds(220, 260, 190, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setText("ID del estadio: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 300, 100, 15);

        getContentPane().add(cbxIDEstadio);
        cbxIDEstadio.setBounds(220, 300, 28, 20);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/BotonVolver.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(110, 350, 100, 25);

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/BotonAceptar.png"))); // NOI18N
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setMaximumSize(new java.awt.Dimension(451, 411));
        btnGuardar.setMinimumSize(new java.awt.Dimension(451, 411));
        btnGuardar.setPreferredSize(new java.awt.Dimension(451, 411));
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(230, 350, 91, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 153));
        jLabel8.setText("Marcador Local:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 180, 110, 15);
        getContentPane().add(MarcadorL);
        MarcadorL.setBounds(220, 180, 190, 20);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pack/Media/FondoTablas.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 730, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Modificar v=new Modificar();
        v.setVisible(true);
        this.setVisible(false);
        
        //LIMPIAR PANTALLA ANTES DE SALIR
        MarcadorL.setText("");
        MarcadorV.setText("");
        cbxIDEstadio.removeAllItems();
        cbxIDJornada.removeAllItems();
        cbxIDPartido.removeAllItems();
        fecha.setText("");
        nomEquipoL.setText("");
        nomEquipoV.setText(""); 
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPartidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPartidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MarcadorL;
    private javax.swing.JTextField MarcadorV;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxIDEstadio;
    private javax.swing.JComboBox<String> cbxIDJornada;
    private javax.swing.JComboBox<String> cbxIDPartido;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nomEquipoL;
    private javax.swing.JTextField nomEquipoV;
    // End of variables declaration//GEN-END:variables
}
